### ISSUE TITLE
Installation Issue on lem-frontend-electron 

### ISSUE THREAD

**Issue by t-cool** [cxxxr/lem#165]
I cannot install lem-frontend-electron using npm.

```
$ node -v
v8.9.3
$ npm -v
5.5.1
$ npm install -g cxxxr/lem
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: github:cxxxr/lem.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/t-cool/.npm/_logs/2018-03-10T00_43_59_903Z-debug.log
```

2018-03-10T00_43_59_903Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/t-cool/.nvm/versions/node/v8.9.3/bin/node',
1 verbose cli   '/Users/t-cool/.nvm/versions/node/v8.9.3/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cxxxr/lem' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose npm-session fdb11761c3557680
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for github:cxxxr/lem Non-registry package missing package.json: github:cxxxr/lem.
8 verbose stack Error: Non-registry package missing package.json: github:cxxxr/lem.
8 verbose stack     at BB.join (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/pacote/lib/finalize-manifest.js:160:23)
8 verbose stack     at tryCatcher (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
8 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
8 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
8 verbose stack     at Promise.eval (eval at thenCallback (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
8 verbose stack     at Promise._settlePromise (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
8 verbose stack     at Promise._settlePromise0 (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
8 verbose stack     at Promise._settlePromises (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
8 verbose stack     at Async._drainQueue (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
8 verbose stack     at Async._drainQueues (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
8 verbose stack     at Immediate.Async.drainQueues (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
8 verbose stack     at runCallback (timers.js:789:20)
8 verbose stack     at tryOnImmediate (timers.js:751:5)
8 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
9 verbose cwd /Users/t-cool
10 verbose Darwin 17.4.0
11 verbose argv "/Users/t-cool/.nvm/versions/node/v8.9.3/bin/node" "/Users/t-cool/.nvm/versions/node/v8.9.3/bin/npm" "install" "-g" "cxxxr/lem"
12 verbose node v8.9.3
13 verbose npm  v5.5.1
14 error code ENOPACKAGEJSON
15 error package.json Non-registry package missing package.json: github:cxxxr/lem.
16 error package.json npm can't find a package.json file in your current directory.
17 verbose exit [ 1, true ]
```

**Comment by t-cool** [comment]
@asciian 
Thank you for your help!

When I start the editor and type M-x, the error happens.
I cannot edit the buffer after the error happens.

I checked the error in DevTool and the console says:
```
/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/node_modules/vscode-jsonrpc/lib…:138 Uncaught Error: Connection is closed.
    at new ConnectionError (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/node_modules/vscode-jsonrpc/lib…:138)
    at throwIfClosedOrDisposed (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/node_modules/vscode-jsonrpc/lib…:613)
    at Object.sendNotification (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/node_modules/vscode-jsonrpc/lib…:667)
    at HTMLElement.emitInput (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/lem-frontend-electron/lem-edito…:207)
    at LemEditor.window.onkeydown (/Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/lem-frontend-electron/lem-edito…:140)
ConnectionError @ /Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/node_modules/vscode-jsonrpc/lib…:138
throwIfClosedOrDisposed @ /Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/node_modules/vscode-jsonrpc/lib…:613
sendNotification @ /Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/node_modules/vscode-jsonrpc/lib…:667
emitInput @ /Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/lem-frontend-electron/lem-edito…:207
LemEditor.window.onkeydown @ /Users/t-cool/.nvm/versions/node/v8.9.3/lib/node_modules/lem/lem-frontend-electron/lem-edito…:140
```

**Comment by t-cool** [comment]
There seems to be a problem around here:
https://github.com/cxxxr/lem/blob/master/lem-frontend-electron/lem-editor/lem-editor.js#L206

**Comment by t-cool** [comment]
@asciian 

The installation issue was solved, so I'll close this issue.

I'll make another issue on M-x bug.

Can you push the claim button to release the budget?

**Comment by asciian** [comment]
@t-cool Okay. Could you open new issue about that problem? I'll tackle it.
